# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'swift超级猜图' do

pod 'SnapKit', '~> 0.16.0'

end

